name: Auto-Merge
on:
  pull_request_target:
    types: [labeled]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: alexwilson/enable-github-automerge-action@da66042c5523b308acdfa0e5b0e2773f5297a054
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
